name: sdlf
toolchainRegion: us-east-1
forceDependencyRedeploy: true
groups:
  - name: foundations
    path: manifests/foundations-module.yaml
targetAccountMappings:
  - alias: primary
    accountId:
      valueFrom:
        envVariable: PRIMARY_ACCOUNT
    default: true
    regionMappings:
      - region: us-east-1
        default: true
